# Automatically generated by tools/update-init-collections
from GoldPiece import GoldPiece
from Haymaker import Haymaker
from LeftHook import LeftHook
from Punch import Punch
from Rock import Rock
from Roll import Roll
from Scythe import Scythe
