#!/usr/bin/python

import sys
import getopt

import common

def usage():
        print """Usage: minmax <file> [ <file> ... ]
"""

try:
        optlist, args = getopt.gnu_getopt(
	                sys.argv[1:],
			'h?',
			['help'])
except getopt.GetoptError, err:
	print str(err)
	usage()
	sys.exit(1)
							  
for o, a in optlist:
        if o in ('-h', '--help', '-?'):
		usage()
		sys.exit(0)
        else:
                usage()
		sys.exit(1)

if len(args) == 0:
	usage()
	sys.exit(1)

minv = 1e6
maxv = -1e6

def transform_coords(x, y, f):
	return (x, y)

for n in args:
	MAX_X, stride, values = common.load_to_array(
        				None, {'file': n}, transform_coords)

	for x in range(0, MAX_X):
		for y in range(0, MAX_X-x):
                	v = float(values[x][y])
			minv = min(minv, v)
			maxv = max(maxv, v)
			
print "minv=" + str(minv)
print "maxv=" + str(maxv)
