#!/usr/bin/python

######
# List details of an account

import sys
import getopt

from Database import DB
from Actor import Actor

def usage():
	print """Usage: accsnoop -a [options]
       accsnoop [options] { <account> | -i <account-id> }
Options:
\t-a, --all\t\tList all accounts
\t-i, --id=<account-id>\tSelect account by ID
\t-b, --brief\t\tShow brief listing (colon separated)
\t-p, --pretty\t\tShow pretty brief listing (formatted for humans)
"""

try:
	optlist, args = getopt.gnu_getopt(sys.argv[1:], 'h?abpi:', ['help', 'all', 'brief', 'pretty', 'id='])
except getopt.GetoptError, err:
	print str(err)
	usage()
	sys.exit(1)

show_all = False
acid = None
acc_format = """%(uname)s (%(aid)d)
  %(email)s
  %(rname)s"""
char_format = """    %(cname)s (%(cid)d), %(align)s"""

for o, a in optlist:
	if o in ('-h', '-?', '--help'):
		usage()
		sys.exit(0)
	elif o in ('-a', '--all'):
		show_all = True
	elif o in ('-i', '--id'):
		acid = int(a)
	elif o in ('-b', '--brief'):
		acc_format = "%(aid)d:%(uname)s:%(email)s:%(nchars)d:%(rname)s"
		char_format = ""
	elif o in ('-p', '--pretty'):
		acc_format = "%(uname)s (%(aid)d): %(rname)s\t%(email)s"
		char_format = "  %(cname)s (%(cid)d), %(align)s"
	else:
		usage()
		sys.exit(1)

if not (len(args) == 1 and acid == None and not show_all) \
	   and not (len(args) == 0 and (acid != None or show_all)):
	usage()
	sys.exit(1)

params = {}
sel_filter = ""
if not show_all:
	if acid != None:
		sel_filter = " AND account.account_id=%(acid)s"
		params['acid'] = acid
	else:
		sel_filter = " AND username=%(uname)s"
		params['uname'] = args[0]

acur = DB.cursor()
acur.execute("SELECT account.account_id, username, realname, email, "
			 + "     COUNT(actor_id)"
			 + " FROM account, account_actor"
			 + " WHERE account.account_id = account_actor.account_id " + sel_filter
			 + " GROUP BY account.account_id, username, realname, email",
			 params)

ccur = DB.cursor()

row = acur.fetchone()
while row != None:
	data = { 'aid': int(row[0]),
			 'uname': row[1],
			 'rname': row[2],
			 'email': row[3],
			 'nchars': row[4] }

	if data['rname'] == None: data['rname'] = ""
	if data['email'] == None: data['email'] = ""

	print acc_format % data

	if char_format != "":
		ccur.execute("SELECT id, name FROM actor, account_actor"
					 + " WHERE actor.id = account_actor.actor_id"
					 + "   AND account_actor.account_id = %(aid)s",
					 data)
		crow = ccur.fetchone()
		while crow != None:
			data['cid'] = int(crow[0])
			actor = Actor.load(int(crow[0]))
			data['cname'] = actor.name
			data['align'] = actor.align
			print char_format % data
			crow = ccur.fetchone()

	row = acur.fetchone()
