#!/usr/bin/python

def usage():
	print """Usage: addclass { <playername> | -i <actorid> } <propertyname> <classname> [class-parameters...]
Add a complete class to an actor object.

Class parameters may be a string, integer or float, or one of the
special cases:

\t:c\t\tThe current player/actor
\t:p<n>\t\tActor number <n>
\t:P<name>\t\tPlayer name <name>

Options:
\t-i, --id=<n>\t\tModify actor number <id>
"""

import sys
import getopt

from Player import Player
from Actor import Actor
from Alignment import Alignment
from Database import DB
import Util


try:
	optlist, args = getopt.gnu_getopt(sys.argv[1:], 'h?i:', ['help', 'id='])
except getopt.GetoptError, err:
	print str(err)
	usage()
	sys.exit(1)

aid = None

for o, a in optlist:
	if o in ('-h', '-?', '--help'):
		usage()
		sys.exit(0)
	elif o in ('-i', '--id'):
		aid = int(a)
	else:
		usage()
		sys.exit(0)

if len(args) < 2:
	usage()
	sys.exit(1)

if aid is not None:
	p = Actor.load(aid)
else:
	p = Player.load_by_name(args.pop(0))

if p is None:
    print "Player not found"
    sys.exit(1)

classname = args[1]
module = __import__(classname, globals(), locals(), [], -1)
cls = module.__dict__[classname]

params = [ Util.retype(x, p) for x in args[2:] ]
obj = cls(*params)

setattr(p, args[0], obj)
p.save()

DB.commit()
