#!/usr/bin/python

"""Add items to a player's inventory"""

import sys
from optparse import OptionParser

from Player import Player
from Item import Item
from Database import DB
import GameUtil


def add_item(name, item_class_name, count):
    """Adds count instances of the given item to the given player's inventory.  
       Defined as such to simplify refactoring into a UI-driven class"""

    # Get the player
    p = Player.load_by_name(name)

    # Now get the requested item class
    item_class = Item.get_class(item_class_name)

    item = item_class()
    if count > 0:
        item.count = count

	# Now just add the inventory to the player
	p.inventory.add(item)
	
	# TODO: insert something witty here.  If we were REALLY feeling ambitious, 
	#       we could even have it pick a saying at random from a list 
	p.message("Your friendly neighbourhood Sourceror appears, gives you an item, and vanishes in a burst of code.", "rodney")
	p.message("You gain " + str(count) + " " + item_class.name_for(count))

	GameUtil.save()
	GameUtil.flush_cache()
	DB.commit()
    

parser = OptionParser(usage='%prog [options] <player_name> <item_class>')
parser.add_option('-c', '--count', type='int', default=1, help="Number of items to remove. [Default: %default]")

options, args = parser.parse_args()

if len(args) != 2:
	parser.error("Incorrect number of arguments")

player_name, item_class = args
add_item(player_name, item_class, count)
