#!/usr/bin/python

def usage():
	print """Usage: addtrigger { <playername> | -i <actorid> } <trigger-type> [parameters...]
Add a trigger to an actor object or one of its constituents.

Class parameters may be a string, integer or float, or one of the
special cases:

\t:c\t\tThe current player/actor
\t:p<n>\t\tActor number <n>
\t:P<name>\t\tPlayer name <name>

Options:
\t-i, --id=<n>\t\tModify actor number <id>
"""

import sys
import getopt

from Player import Player
from Actor import Actor
from Alignment import Alignment
from Database import DB
import Util


try:
	optlist, args = getopt.gnu_getopt(sys.argv[1:], 'h?i:', ['help', 'id='])
except getopt.GetoptError, err:
	print str(err)
	usage()
	sys.exit(1)

aid = None

for o, a in optlist:
	if o in ('-h', '-?', '--help'):
		usage()
		sys.exit(0)
	elif o in ('-i', '--id'):
		aid = int(a)
	else:
		usage()
		sys.exit(0)

if len(args) < 1:
	usage()
	sys.exit(1)

if aid is not None:
	p = Actor.load(aid)
else:
	p = Player.load_by_name(args.pop(0))

if p is None:
    print "Player not found"
    sys.exit(2)

if len(args) < 1:
	usage()
	sys.exit(1)

classname = args[1]
module = __import__(classname, globals(), locals(), [], -1)
cls = module.__dict__[classname]

if not isinstance(cls, Trigger):
	print "Class", cls.__name__, "is not a Trigger type"
	sys.exit(3)

params = [ Util.retype(x, current) for x in args[2:] ]
trigger = cls(*params) # Registers automatically with p
p.save()

DB.commit()
