#!/usr/bin/python

import os
import os.path

from PIL import Image, ImageChops

TILE_PATH = '../server_root/tiles/'


class ColourFilter(object):
	def __init__(self, outpath, r, g, b):
		self.outpath = outpath
		self.r = int(r * 255)
		self.g = int(g * 255)
		self.b = int(b * 255)

	def filter(self, im):
		overlay = Image.new('RGBA', im.size, (self.r, self.g, self.b))
		return ImageChops.multiply(overlay, im)

	def outfile(self, f):
		return os.path.join(self.outpath, f)


FILTERS = [
	ColourFilter('night', 0.4, 0.4, 0.7),
	ColourFilter('sunrise', 1.0, 0.95, 0.7),
	ColourFilter('sunset', 1.0, 0.9, 0.75),
]


def filter_all(filters, path):
	for dayt in os.listdir(path):
		if dayt.startswith('.') or not dayt.endswith('.png'):
			continue
		im = Image.open(os.path.join(path, dayt))
		for filter in filters:
			dst = os.path.join(path, filter.outfile(dayt))
			if os.path.exists(dst):
				print "Skipping existing tile", dst
				continue
			out = filter.filter(im)
			out.save(dst)


filter_all(FILTERS, 'server_root/tiles/')

