#!/usr/bin/python

import os
import os.path
import BaseConfig

def clean_cache(path):
	"""Delete files from a given cache directory"""
	count = 0
	for fn in os.listdir(path):
		full_name = os.path.join(path, fn)
		if os.path.isfile(full_name):
			os.remove(full_name)
			count += 1
	print "  Removed", count, "cached files from", os.path.basename(path)
	return count

def clean_image_caches(image_set):
	"""Clean up all the cache directories for this image set"""
	print " Cleaning", os.path.basename(image_set)
	count = 0
	count += clean_cache(os.path.join(image_set, "cache"))
	count += clean_cache(os.path.join(image_set, "component"))
	count += clean_cache(os.path.join(image_set, "fragment"))
	print "   = ", count, "files total"
	return count

###################################

image_base = os.path.join(BaseConfig.base_dir, "server_root", "img", "terrain")

count = 0
for image_set in os.listdir(image_base):
	if (os.path.isdir(os.path.join(image_base, image_set))
		and os.path.isfile(os.path.join(image_base, image_set, "metadata.txt"))):
		# We've got an image set, so we can process it
		count += clean_image_caches(os.path.join(image_base, image_set))

print count, "files cleaned"
