#!/usr/bin/python

import sys
import getopt
from Actor import Actor
from Item import Item

def usage():
	print """Usage: itemsnoop <itemid>
"""

try:
	optlist, args = getopt.gnu_getopt(sys.argv[1:], 'h?', ['help'])
except getopt.GetoptError, err:
	print str(err)
	usage()
	sys.exit(1)

for o, a in optlist:
	if o in ('-h', '-?', '--help'):
		usage()
		sys.exit(0)
	else:
		usage()
		sys.exit(1)

if len(args) != 1:
	usage()
	sys.exit(1)

i = Item.load(int(args[0]), allprops=True)
if i == None:
	print "Item ID", args[0], "not found"
	sys.exit(1)

print "type\t" + i.ob_type()
for (k, v) in i.__dict__.items():
    print str(k) + "\t" + str(v)
