#!/usr/bin/python

import sys
import getopt
from Position import Position
from Location import Location
import Util
import Context

def usage():
	print """Usage: locsnoop <x> <y> <layer>
"""

try:
	optlist, args = getopt.gnu_getopt(sys.argv[1:], 'h?', ['help'])
except getopt.GetoptError, err:
	print str(err)
	usage()
	sys.exit(1)

for o, a in optlist:
	if o in ('-h', '-?', '--help'):
		usage()
		sys.exit(0)
	else:
		usage()
		sys.exit(1)

if len(args) != 3:
	usage()
	sys.exit(1)

Context.context = Context.ADMIN_CTX

pos = Position(int(args[0]), int(args[1]), args[2])
loc = Location.load_by_pos(pos, allprops=True)

if loc == None:
	print "Location not found"
	sys.exit(1)

while loc != None:
	info = loc.context_get()
	ind = Util.info_key_length(info)+1
	print ("%-"+str(ind+1)+"s%s") % ("type:", loc.ob_type())
	Util.render_info(info, sys.stdout, indent=ind)
	print "------------------------------"
	loc = loc._underneath
