#!/usr/bin/python

"""Create a new account"""

import sys
import random
from optparse import OptionParser

from Database import DB
import GameUtil


def create_user(username, password=None, realname=None, email=None):
	"""Create a user account with the username given.

	Also store a real name and e-mail address if given.

	If a password is given, store it as the password for the account,
	otherwise generate a random password and print the username and
	password pair to stdout.

	"""
	if not password:
		valid = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_=+,.<>:;!$%^&*()?/"
		password = ""
		for i in xrange(12):
			password += random.choice(valid)
		print username, password

	cur = DB.cursor()
	cur.execute("INSERT INTO account (username, password, realname, email)"
			+ " VALUES (%(uname)s, %(pwd)s, %(rname)s, %(email)s)",
			{ "uname": username,
			  "pwd": password,
			  "rname": realname,
			  "email": email })

	DB.commit()


parser = OptionParser(usage='%prog [options] <username>')
parser.add_option('-p', '--password', help="Set password (otherwise, generate a random one and print it)")
parser.add_option('-r', '--realname', help="Set a real name for the account")
parser.add_option('-e', '--email', help="Set an e-mail address for the account")

options, args = parser.parse_args()

if len(args) != 1:
	parser.error('invalid number of arguments')

username = args[0]
create_user(username, options.password, options.realname, options.email)
