#!/usr/bin/python

######
# Create a new location

from Location import Location
from Position import Position
from Database import DB
import GameUtil

loc = Location(Position(0, 0, 'main'))
loc.taxi = 1729
loc.moo = 'Moo'

overlay = Location(Position(0, 0, 'main'))
loc.add_overlay(overlay)
overlay.taxi = 1200

GameUtil.save()

DB.commit()
