#!/usr/bin/python

######
# Create a new location

import sys
import getopt

from wor.db import db
from wor.world.location import Location
from Position import Position
import GameUtil

def usage():
#	print """Usage: newlocation <x> <y> <layer> <class> [<class-options>]
#Create a new location, of the given class, with the constructor given
#"""
	print """Usage: newlocation <x> <y> <layer>
Create a new location.
"""

try:
	optlist, args = getopt.gnu_getopt(sys.argv[1:], 'h?i:', ['help'])
except getopt.GetoptError, err:
	print str(err)
	usage()
	sys.exit(1)

aid = None

for o, a in optlist:
	if o in ('-h', '-?', '--help'):
		usage()
		sys.exit(0)
	else:
		usage()
		sys.exit(0)

#if len(args) < 4:
if len(args) != 3:
	usage()
	sys.exit(1)

pos = Position(int(args[0]), int(args[1]), args[2])

#overlay = Location(Position(0, 0, 'main'))
#loc.add_overlay(overlay)
#overlay.taxi = 1200
db.world.set_location(position, Location())

db.commit()
