#!/usr/bin/python

######
# Create a new player

from Player import Player
from Item import Item
from Alignment import Alignment
from Database import DB
from Rock import Rock
import GameUtil

p = Player('darksatanic', 'wor', Alignment.WOOD)
rock = Rock()
p.inventory.add(rock)

GameUtil.save()

DB.commit()
