#!/usr/bin/python

######
# Create a new player

import sys
import getopt

from Player import Player
from Item import Item
from Alignment import Alignment
from Database import DB
from Items.Rock import Rock
import GameUtil

def usage():
	print """Usage: newplayer [options] { <account> | -i <account-id> } <playername>
Options:
\t-a, --align=<align>\t\tAlignment. Values can be:
\t\t\t\t\t\tw\twood
\t\t\t\t\t\te\tearth
\t\t\t\t\t\tf\tfire
\t\t\t\t\t\tt\twater
\t\t\t\t\t\tm\tmetal
\t-i, --id=<account-id>\t\tAccount ID to create player in
"""

align_map = { 'w': Alignment.WOOD,
			  'e': Alignment.EARTH,
			  'f': Alignment.FIRE,
			  't': Alignment.WATER,
			  'm': Alignment.METAL }

try:
	optlist, args = getopt.gnu_getopt(sys.argv[1:], 'h?a:i:', ['help', 'align=', 'id='])
except getopt.GetoptError, err:
	print str(err)
	usage()
	sys.exit(1)

align = align_map['w']
acid = None

for o, a in optlist:
	if o in ('-h', '-?', '--help'):
		usage()
		sys.exit(0)
	elif o in ('-a', '--align'):
		align = align_map[a]
	elif o in ('-i', '--id'):
		acid = int(a)
	else:
		usage()
		sys.exit(0)

if acid == None and len(args) != 2 or acid != None and len(args) != 1:
	usage()
	sys.exit(1)

if acid == None:
	cur = DB.cursor()
	cur.execute("SELECT account_id FROM account WHERE username=%(uname)s",
			{ "uname": args.pop(0) })
	acid = cur.fetchone()[0]

p = Player(args[0], align)
print "Created player id", p._id
rock = Rock()
p.inventory.add(rock)

GameUtil.save()

cur = DB.cursor()
cur.execute("INSERT INTO account_actor (account_id, actor_id)"
		+ " VALUES (%(acid)s, %(actid)s)",
		{ "acid": acid,
		  "actid": p._id })

DB.commit()
