#!/usr/bin/python

######
# Modify a property of a player

import sys

from Player import Player
from Alignment import Alignment
from Database import DB

p = Player.load_by_name(sys.argv[1])
if p == None:
    print "Player not found"
    sys.exit(1)

# Convert the string parameter from the command line to an appropriate
# type
value = sys.argv[3]
try:
    p[sys.argv[2]] = int(value)
except:
    try:
        p[sys.argv[2]] = float(value)
    except:
        p[sys.argv[2]] = str(value)
    
p.save()

DB.commit()
